#ifndef ENUMCOMMANDTYPES_HPP
#define ENUMCOMMANDTYPES_HPP

enum class CommandTypes
{
    LOOK_AT,
    ROTATE,
    MOVE_IN_DIR,
    MOVE_LEFT,
    MOVE_RIGHT,
    MOVE_UP,
    MOVE_DOWN,
    MOVE_UP_LEFT,
    MOVE_UP_RIGHT,
    MOVE_DOWN_LEFT,
    MOVE_DOWN_RIGHT,
    ACTION1,
    ACTION2,
    ACTION3,
    START_BLOCKING,
    STOP_BLOCKING,
};

#endif // ENUMCOMMANDTYPES_HPP
