#ifndef ENUMCOMMANDTYPES_HPP
#define ENUMCOMMANDTYPES_HPP

enum class CommandTypes
{
    LOOK_AT,
    ROTATE,
    MOVE_IN_DIR,
    MOVE_LEFT,
    MOVE_RIGHT,
    MOVE_UP,
    MOVE_DOWN,
    MOVE_UP_LEFT,
    MOVE_UP_RIGHT,
    MOVE_DOWN_LEFT,
    MOVE_DOWN_RIGHT,
    ACTION_1,
    ACTION_2,
    SPECIAL_ACTION,
    ACTION_START,
    ACTION_STOP,
};

#endif // ENUMCOMMANDTYPES_HPP
